name: ext_plus
description: "A Flutter package providing utility methods and extensions for String manipulations and validations with comprehensive null check handling.
"
version: 0.0.8+3
repository: https://github.com/ChandanKumar-Singh/packages/blob/main/pack_plug/ext_plus/example/lib/main.dart
homepage:  https://github.com/ChandanKumar-Singh/packages/blob/main/pack_plug/ext_plus/example/lib/main.dart

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^6.0.3
  flutter:
    sdk: flutter
  flutter_smart_dialog: ^4.9.7+9
  fluttertoast: ^8.2.6
  http: ^1.2.1
  logger: ^2.4.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
