name: ext_plus
description: "A Flutter package providing utility methods and extensions for String manipulations and validations with comprehensive null check handling.
"
version: 0.1.0
repository: https://github.com/ChandanKumar-Singh/packages/blob/main/pack_plug/ext_plus/example/lib/main.dart
homepage:  https://github.com/ChandanKumar-Singh/packages/blob/main/pack_plug/ext_plus/example/lib/main.dart

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^6.0.3
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^2.1.0
  flutter_smart_dialog: ^4.9.8+6
  fluttertoast: ^8.2.12
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  shared_preferences: ^2.5.2
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
