// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0SDClYHW4iNI1UgalPoYPHEiPUuqswps',
    appId: '1:684446974160:android:b15ebd815014b65ad31ed5',
    messagingSenderId: '684446974160',
    projectId: 'ecom-kcks',
    storageBucket: 'ecom-kcks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6AHJl60IVV7StnIg01-asX25-VbxDVfE',
    appId: '1:684446974160:ios:8e589078bdcbf14ed31ed5',
    messagingSenderId: '684446974160',
    projectId: 'ecom-kcks',
    storageBucket: 'ecom-kcks.appspot.com',
    androidClientId: '684446974160-1cqbaakqi4960oc99gbr9unj7h15dmoo.apps.googleusercontent.com',
    iosClientId: '684446974160-mipb74cuc4113jfn9uccgurdk63h3sqr.apps.googleusercontent.com',
    iosBundleId: 'com.ecom.ulearning',
  );
}
