name: ulearning_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  google_sign_in: ^6.2.1
  flutter_smart_dialog: ^4.9.7+7
  flutter_custom_tabs: ^2.0.0+1
  equatable: ^2.0.5
  provider: ^6.1.2
  awesome_bottom_bar: ^1.2.4
  shared_preferences: ^2.2.3
  iconic: ^0.1.0
  vibration: ^1.9.0
  just_audio: ^0.9.38
  card_swiper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/sounds/

  fonts:
    - family: RobotoSerif
      fonts:
        - asset: assets/fonts/RobotoSerif-VariableFont_GRAD,opsz,wdth,wght.ttf
          weight: 400
        - asset: assets/fonts/RobotoSerif-Italic-VariableFont_GRAD,opsz,wdth,wght.ttf
          weight: 400
          style: italic
